- x1:
    z:        -40.
    nWire:    &xnwire 56
    cellSize: &cell 20.
    angle:    &xangle 0.
    center:    9.107
- x2:
    z:        -24.
    nWire:    *xnwire
    cellSize: *cell
    angle:    *xangle
    center:    8.857
- u1:
    z:        -8.
    nWire:    &uvnwire 44
    cellSize: *cell
    angle:    &uangle 36.8699
    center:   &c1 6.7606
- u2:
    z:         8.
    nWire:    *uvnwire
    cellSize: *cell
    angle:    *uangle
    center:   &c2 7.0106
- v1:
    z:         24.
    nWire:    *uvnwire
    cellSize: *cell
    angle:    &vangle -36.8699
    center:   *c1
- v2:
    z:         40.
    nWire:    *uvnwire
    cellSize: *cell
    angle:    *vangle
    center:   *c2
