# cell config = L R L R L R
- x1:
    z:        -40.
    nWire:    &xnwire 56
    cellSize: &cell   20.
    angle:    &xangle  0.     #vertical/y-axis = 0
    center:   28.375  # L
#    center:   28.625  # R
- x2:
    z:       -24.
    nWire:    *xnwire
    cellSize: *cell
    angle:    *xangle
    center:   28.625  # R
#    center:   28.375  # L
- u1:
    z:        -8.
    nWire:    &uvnwire 44
    cellSize: *cell
    angle:    &uangle -36.8699 # plan angle , positive = toward y-axis
    center:   22.375  # L
#    center:   22.625  # R
- u2:
    z:        8.
    nWire:    *uvnwire
    cellSize: *cell
    angle:    *uangle
#    center:   22.375  # L
    center:   22.625  # R
- v1:
    z:        24.
    nWire:    *uvnwire
    cellSize: *cell
    angle:    &vangle 36.8699
    center:   22.375  # L
#    center:   22.625  # R
- v2:
    z:        40.
    nWire:    *uvnwire
    cellSize: *cell
    angle:    *vangle
#    center:   22.375  # L
    center:   22.625  # R
