# SMWDC-L : R L L R L R
- x1:
    z:       -40.
    nWire:    &xnwire 56
    cellSize: &cell 20.
    angle:    &xangle 0.
    center:   48.143
- x2:
    z:       -24.
    nWire:    *xnwire
    cellSize: *cell
    angle:    *xangle
    center:   47.893
- u1:
    z:        -8.
    nWire:    &uvnwire 44
    cellSize: *cell
    angle:    &uangle -36.8699
    center:   37.9894
- u2:
    z:         8.
    nWire:    *uvnwire
    cellSize: *cell
    angle:    *uangle
    center:   38.2394
- v1:
    z:        24.
    nWire:    *uvnwire
    cellSize: *cell
    angle:    &vangle 36.8699
    center:   37.9894
- v2:
    z:        40.
    nWire:    *uvnwire
    cellSize: *cell
    angle:    *vangle
    center:   38.2394
