# SMWDC-L : R L L R L R
- x1:
    z:       -40.
    nWire:    &xnwire 56
    cellSize: &cell 20.
    angle:    &xangle 0.
    center:   48.143  # R
#    center:   47.893  # L
- x2:
    z:       -24.
    nWire:    *xnwire
    cellSize: *cell
    angle:    *xangle
    center:   47.893  # L
#    center:   48.143  # R
- u1:
    z:        -8.
    nWire:    &uvnwire 44
    cellSize: *cell
    angle:    &uangle -36.8699
    center:   &center1 37.9894  # L
#    center:   &center1 38.2394  # R

- u2:
    z:         8.
    nWire:    *uvnwire
    cellSize: *cell
    angle:    *uangle
    center:   &center2 38.2394  # R
#    center:   &center2 37.9894  # L

- v1:
    z:        24.
    nWire:    *uvnwire
    cellSize: *cell
    angle:    &vangle 36.8699
    center:   *center1
- v2:
    z:        40.
    nWire:    *uvnwire
    cellSize: *cell
    angle:    *vangle
    center:   *center2
